name: CI and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test

  deploy:
    name: Deploy to Firebase
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THERESNOTIME_CO_UK }}'
          channelId: live
          projectId: theresnotime-co-uk